alter table operation add column prediction_score varchar(20);
alter table operation add column prediction_result varchar(20);
alter table operation drop column detected_rules;

CREATE TABLE detected_operation_rule (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE,
   created_by VARCHAR(255),
   updated_on TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   deleted VARCHAR(1),
   operation_id BIGINT,
   rule_id BIGINT,
   CONSTRAINT pk_detected_operation_rule PRIMARY KEY (id)
);

ALTER TABLE detected_operation_rule ADD CONSTRAINT FK_DETECTED_OPERATION_RULE_ON_OPERATION FOREIGN KEY (operation_id) REFERENCES operation (id);

ALTER TABLE detected_operation_rule ADD CONSTRAINT FK_DETECTED_OPERATION_RULE_ON_RULE FOREIGN KEY (rule_id) REFERENCES rule (id);

