CREATE TABLE subscription_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE,
   created_by VARCHAR(255),
   updated_on TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   deleted VARCHAR(1),
   name VARCHAR(255) NOT NULL,
   description VARCHAR(255),
   CONSTRAINT pk_subscription_plan PRIMARY KEY (id)
);

CREATE TABLE subscription_plan_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE,
   created_by VARCHAR(255),
   updated_on TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   deleted VARCHAR(1),
   parameter_name VARCHAR(255) NOT NULL,
   parameter VARCHAR(255) NOT NULL,
   value VARCHAR(255) NOT NULL,
   subscription_plan_id BIGINT,
   CONSTRAINT pk_subscription_plan_detail PRIMARY KEY (id)
);

ALTER TABLE subscription_plan_detail ADD CONSTRAINT FK_SUBSCRIPTION_PLAN_DETAIL_ON_SUBSCRIPTION_PLAN FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id);

ALTER TABLE organization ADD subscription_plan_id BIGINT;

ALTER TABLE organization ADD CONSTRAINT FK_SUBSCRIPTION_PLAN_ORGANIZATION FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id);