CREATE TABLE organization_parameter_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    parameter_id BIGINT NOT NULL,
    CONSTRAINT pk_parameter_option PRIMARY KEY (id)
);