drop table aggregate;

drop table criteria;

CREATE TABLE criterion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE,
   created_by VARCHAR(255),
   updated_on TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   deleted VARCHAR(1),
   name VARCHAR(255),
   window_type VARCHAR(255),
   aggregation_name VARCHAR(255),
   aggregation_type VARCHAR(255),
   aggregation_path VARCHAR(255),
   aggregation_value VARCHAR(255),
   rule_id BIGINT,
   is_active VARCHAR(1),
   CONSTRAINT pk_criterion PRIMARY KEY (id)
);

ALTER TABLE criterion ADD CONSTRAINT FK_CRITERION_ON_RULE FOREIGN KEY (rule_id) REFERENCES rule (id);

CREATE TABLE criterion_condition (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE,
   created_by VARCHAR(255),
   updated_on TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   deleted VARCHAR(1),
   field_name VARCHAR(255),
   field_path VARCHAR(255),
   operator VARCHAR(255),
   value VARCHAR(255),
   criterion_id BIGINT,
   CONSTRAINT pk_criterion_condition PRIMARY KEY (id)
);

ALTER TABLE criterion_condition ADD CONSTRAINT FK_CRITERION_CONDITION_ON_CRITERION FOREIGN KEY (criterion_id) REFERENCES criterion (id);